export const TIERS = [
  {
    id: "plastic",
    name: "Plástico",
    color: "#f59e0b",
    icon: "🧴",
    wasteIcon: "🗑",
    processedIcon: "♻",
    wasteSpawnRate: 6,
    energyWasteRate: 12,
    processTime: 4,
    energyType: "diesel",
    energyIcon: "🛢",
    energyWasteIcon: "☢",
    energyColor: "#78716c",
    sellValue: 10,
    unlockCost: 500,
  },
  {
    id: "paper",
    name: "Papel",
    color: "#60a5fa",
    icon: "📄",
    wasteIcon: "🗑",
    processedIcon: "📋",
    wasteSpawnRate: 5,
    energyWasteRate: 10,
    processTime: 4,
    energyType: "coal",
    energyIcon: "🪨",
    energyWasteIcon: "☣",
    energyColor: "#57534e",
    sellValue: 15,
    unlockCost: 1000,
  },
  {
    id: "glass",
    name: "Vidrio",
    color: "#34d399",
    icon: "🍾",
    wasteIcon: "🗑",
    processedIcon: "🔷",
    wasteSpawnRate: 7,
    energyWasteRate: 14,
    processTime: 5,
    energyType: "gas",
    energyIcon: "💨",
    energyWasteIcon: "☠",
    energyColor: "#6ee7b7",
    sellValue: 20,
    unlockCost: 2000,
  },
  {
    id: "organic",
    name: "Orgánico",
    color: "#c084fc",
    icon: "🌿",
    wasteIcon: "🗑",
    processedIcon: "🌱",
    wasteSpawnRate: 4,
    energyWasteRate: 999,
    processTime: 3,
    energyType: "solar",
    energyIcon: "☀",
    energyWasteIcon: "",
    energyColor: "#fde68a",
    sellValue: 25,
    unlockCost: 4000,
  },
];
